# Our Node base image
FROM node:lts-alpine AS dev

# Copying the package files allows docker to cache node modules
# Installation will only run when dependencies changed
COPY package.json .
COPY package-lock.json .

RUN npm install
RUN apk add --no-cache bash && apk add nmap && apk add curl
CMD ["npm","run", "dev", "--host"]