# Our Node base image
FROM node:lts-bullseye

# Copying the package files allows docker to cache node modules
# Installation will only run when dependencies changed
COPY package.json .
COPY package-lock.json .

RUN npm install
# this is only used for debugging, so uncomment this once it is needed
# RUN apk add --no-cache bash && apk add nmap && apk add curl
# we need the -- before the --host to pass the host to the vite server
CMD ["npm","run", "dev", "--", "--host"]