FROM node:lts-alpine

# Copying the package files allows docker to cache node modules
# Installation will only run when dependencies changed
COPY package.json .
COPY package-lock.json .

COPY . .

RUN npm run build

CMD ["node", "build"]

# CMD ["npm","run", "dev", "--host"]