version: "3.1"

services:
  frontend-prod:
    restart: on-failure
    build:
      context: ./frontend-svelte
      dockerfile: Dockerfile.prod

    environment:
      NODE_ENV: prod
      PASSWORD: ${PASSWORD}
      DB_USER: ${DB_USER}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      AUTH_SECRET: ${AUTH_SECRET}
    ports:
      # The port of the website
      - 3000:3000
    working_dir: /frontend-svelte
    volumes:
      - ./frontend-svelte:/frontend-svelte