version: "3.1"

services:
  frontend-prod:
    restart: on-failure
    build:
      context: ./frontend-svelte
      dockerfile: Dockerfile.prod
    environment:
      NODE_ENV: production
    ports:
      # The port of the website
      - 3000:3000

    # This will make all variables inside the root .env accessible inside the container
    env_file: .env
    volumes:
      - ./frontend-svelte:/frontend-svelte
    working_dir: /frontend-svelte