version: "3.1"

services:
  frontend-dev:
    restart: on-failure
    build:
      context: ./frontend-svelte
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
    ports:
      # The port of the website
      - 5173:5173

    # This will make all variables inside the root .env accessible inside the container
    env_file: .env
    volumes:
      - ./frontend-svelte:/frontend-svelte
    working_dir: /frontend-svelte