version: "3.1"

services:
  frontend-dev:
    restart: on-failure
    build:
      context: ./frontend-svelte
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: development
      PASSWORD: ${PASSWORD}
      DB_USER: ${DB_USER}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
    ports:
      # The port of the website
      - 5173:5173
    volumes:
      - ./frontend-svelte:/frontend-svelte
      # This excludes the node_modules folder from docker volume
      - /frontend-svelte/node_modules
      - /frontend-svelte/.svelte-kit
    working_dir: /frontend-svelte