version: "3.1"

services:
  frontend-dev:
    restart: on-failure
    build:
      context: ./frontend-svelte
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
    ports:
      # The port of the website
      - 5173:5173

    # This will make all variables inside the root .env accessible inside the container
    env_file: .env
    volumes:
      - ./frontend-svelte:/frontend-svelte
    working_dir: /frontend-svelte

  fill-db-with-test-input:
    build:
      context: ./database/tests_docker
      dockerfile: Dockerfile_fill_db_with_test_inputs
    volumes:
      - ./database/tests_docker/sql:/app/sql
      - ./database/tests_docker/fill_for_local_test.py:/app/fill_for_local_test.py

