version: "3.1"

services:
  backend:
    ports:
      # we use nginx to proxy port 4998 to the API_BASE_URL
      - 4000:5000
    environment:
      ENV: "test"
      BACKEND_PORT: 5000

  frontend-prod:
    restart: on-failure
    build:
      context: ./frontend-svelte
      dockerfile: Dockerfile.prod
    environment:
      NODE_ENV: test
      ORIGIN: "https://www.dataframetrainer.com"
      API_BASE_URL: "https://www.dataframetrainer.com:4000"
    ports:
      # The port of the website
      - 4444:3000

volumes:
  dataframetrainer_postgres_test:
    external: true