version: "3.1"

services:
  frontend-dev:
    restart: on-failure
    build:
      context: ./frontend-svelte
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
      - POSTGRES_PASSWORD: ${PASSWORD}
      - POSTGRES_USER: ${DB_USER}
      - POSTGRES_DB: ${DB_NAME}
      - GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      - GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      - AUTH_SECRET: ${AUTH_SECRET}
    ports:
      # The port of the website
      - 5173:5173
    volumes:
      - ./frontend-svelte:/frontend-svelte
    working_dir: /frontend-svelte