version: "3.1"

services:
  frontend:
    build: 
      context: ./frontend-svelte
      dockerfile: Dockerfile.prod
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    env_file: .env
    working_dir: /frontend-svelte
