version: "3.1"

services:
  backend:
    ports:
      - 5000:5000
    environment:
      ENV: "dev"
      BACKEND_PORT: 5000

  frontend-prod:
    restart: on-failure
    build:
      context: ./frontend-svelte
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: development
      ORIGIN: "http://localhost:3000"
      API_BASE_URL: "http://localhost:5000"
    ports:
      # The port of the website
      - 5173:5173
    volumes:
      - ./frontend-svelte:/app
      # This excludes the node_modules folder from docker volume
      - /frontend-svelte/node_modules
      - /frontend-svelte/.svelte-kit
    working_dir: /app

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080