version: "3.1"

services:
  backend:
    ports:
      - 5000:5000
    environment:
      ENV: "prod"
      BACKEND_PORT: 5000

  frontend-prod:
    restart: on-failure
    build:
      context: ./frontend-svelte
      dockerfile: Dockerfile.prod
    environment:
      NODE_ENV: production
      ORIGIN: "https://www.dataframetrainer.com:5000"
    ports:
      # The port of the website
      - 3000:3000

volumes:
  dataframetrainer_postgres:
    external: true