version: "3.1"

services:
  frontend-prod:
    restart: on-failure
    build:
      context: ./frontend-svelte
      dockerfile: Dockerfile.prod
    environment:
      NODE_ENV: production
      ORIGIN: "http://www.dataframetrainer.com"
    ports:
      # The port of the website
      - 3000:3000