version: "3.1"

services:
  frontend-prod:
    restart: on-failure
    build:
      context: ./frontend-svelte
      dockerfile: Dockerfile.prod
    environment:
      NODE_ENV: production
      # PASSWORD: ${PASSWORD}
      # DB_USER: ${DB_USER}
      # DB_PORT: ${DB_PORT}
      # DB_NAME: ${DB_NAME}
      # AUTH_SECRET: ${AUTH_SECRET}
      ORIGIN: "http://localhost:3000"
    ports:
      # The port of the website
      - 3001:3000
    # This will make all variables inside the root .env accessible inside the container
    # try without
    env_file: .env
    volumes:
      - ./frontend-svelte:/frontend-svelte
    working_dir: /frontend-svelte