name: ci

on:
  push:
    branches:
      - 'main'
    paths:
      - *
  pull_request:
  workflow_call:
  pull_request_target:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Setup docker compose
        uses: KengoTODA/actions-setup-docker-compose@v1
      -
        name: Run docker compose
        run: |
          ls -la
          docker compose up -d
      -
        name: Check curl response
        run: |
          response_code=$(curl -o /dev/null -w "%{http_code}" http://127.0.0.1:5000/get_all_challenges/)
          if [ "$response_code" -ne 200 ]; then
            echo "Response code is not 200. Failing the pipeline."
            exit 1
          fi
