name: deploy-to-server

on:
  push:
  pull_request:
  workflow_call:
  workflow_dispatch:

jobs:
  run-e2e-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      PEGSOLITAIRE_KEY: ${{ secrets.PEGSOLITAIRE_KEY }}
    steps:
    - uses: actions/checkout@v3
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3