name: Run Python Tests

on:
  push:
    branches:
      - main
    paths:
      - backend/**
  pull_request:
    paths:
      - backend/**
  workflow_call:
  pull_request_target:

jobs:
  run-pytest-on-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: "backend/requirements*.txt"
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.dev.txt
          pip install -r requirements.txt
      - name: Test with pytest
        run: |
          echo "$(pwd)"
          cat requirements.dev.txt
          python -m pytest tests
