name: Run Python Tests

on:
  push:
    branches:
      - main
    paths:
      - backend/**
  pull_request:
    paths:
      - backend/**
  workflow_call:

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: "backend/requirements*.txt"
      - name: Test with pytest
        run: |
          pytest tests